/// Flutter icons Icons
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Icons
///      fonts:
///       - asset: fonts/Icons.ttf
///
/// 
/// * Modern Pictograms, Copyright (c) 2012 by John Caserta. All rights reserved.
///         Author:    John Caserta
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://thedesignoffice.org/project/modern-pictograms/
/// * Web Symbols, Copyright (c) 2011 by Just Be Nice studio. All rights reserved.
///         Author:    Just Be Nice studio
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://www.justbenicestudio.com/
/// * Entypo, Copyright (C) 2012 by Daniel Bruce
///         Author:    Daniel Bruce
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://www.entypo.com
/// * Material Design Icons, Copyright (C) Google, Inc
///         Author:    Google
///         License:   Apache 2.0 (https://www.apache.org/licenses/LICENSE-2.0)
///         Homepage:  https://design.google.com/icons/
///
import 'package:flutter/widgets.dart';

class CustomIcons {
  CustomIcons._();

  static const _kFontFam = 'Icons';

  static const IconData cancel = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData cancel_1 = const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData cd = const IconData(0xe802, fontFamily: _kFontFam);
  static const IconData record = const IconData(0xe803, fontFamily: _kFontFam);
  static const IconData cancel_circled = const IconData(0xe804, fontFamily: _kFontFam);
  static const IconData assessment = const IconData(0xe805, fontFamily: _kFontFam);
  static const IconData help_circled = const IconData(0xe806, fontFamily: _kFontFam);
  static const IconData vimeo_circled = const IconData(0xf307, fontFamily: _kFontFam);
  static const IconData twitter_circled = const IconData(0xf30a, fontFamily: _kFontFam);
  static const IconData facebook_circled = const IconData(0xf30d, fontFamily: _kFontFam);
  static const IconData gplus_circled = const IconData(0xf310, fontFamily: _kFontFam);
  static const IconData pinterest_circled = const IconData(0xf313, fontFamily: _kFontFam);
  static const IconData tumblr_circled = const IconData(0xf316, fontFamily: _kFontFam);
  static const IconData linkedin_circled = const IconData(0xf319, fontFamily: _kFontFam);
  static const IconData dribbble_circled = const IconData(0xf31c, fontFamily: _kFontFam);
  static const IconData stumbleupon_circled = const IconData(0xf31f, fontFamily: _kFontFam);
  static const IconData lastfm_circled = const IconData(0xf322, fontFamily: _kFontFam);
  static const IconData rdio_circled = const IconData(0xf325, fontFamily: _kFontFam);
  static const IconData spotify = const IconData(0xf327, fontFamily: _kFontFam);
  static const IconData renren = const IconData(0xf33c, fontFamily: _kFontFam);
  static const IconData vkontakte = const IconData(0xf354, fontFamily: _kFontFam);
}
